db_var = {1: {'id': 1,
              'type': 'shirt',
              'image': 'images/shirt/shirt_1.jpg',
              'name': 'Рубашка красивая',
              'description': 'очень красивая рубашка',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          2: {'id': 2,
              'type': 'shirt',
              'image': 'images/shirt/shirt_2.jpg',
              'name': 'Простая рубашка',
              'description': 'Рубаха как рубаха, можно носить',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          3: {'id': 3,
              'type': 'shirt',
              'image': 'images/shirt/shirt_3.jpg',
              'name': 'Рубашка козырная',
              'description': 'Сегодня в моде такие, козырные',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          4: {'id': 4,
              'type': 'shirt',
              'image': 'images/shirt/shirt_4.jpg',
              'name': 'Вая, бля! Чё за рубаха!',
              'description': 'ух, какая! дайте две!',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
            5: {'id': 5,
              'type': 'shirt',
              'image': 'images/shirt/shirt_5.jpg',
              'name': 'РУБАШКА! Всем носить именно такие!',
              'description': 'Новый указ президента',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          6: {'id': 1,
              'type': 'jacket',
              'image': 'images/jacket/jacket_1.jpg',
              'name': 'Фирменная куртка',
              'description': 'Кто не верит FAKE YOU',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          7: {'id': 2,
              'type': 'jacket',
              'image': 'images/jacket/jacket_2.jpg',
              'name': 'Мусорское пальто',
              'description': 'Ты и есть власть!',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          8: {'id': 3,
              'type': 'jacket',
              'image': 'images/jacket/jacket_3.jpg',
              'name': 'Пидорский куртец',
              'description': 'А может и не пидорский, а просто женский',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          9: {'id': 1,
              'type': 'jeans',
              'image': 'images/jeans/jeans_1.jpg',
              'name': 'Джинсы как джинсы',
              'description': 'Такие носят все кому не лень',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          10: {'id': 2,
              'type': 'jeans',
              'image': 'images/jeans/jeans_2.jpg',
              'name': 'Джинсы улучшенные',
              'description': 'Местами обоссаные, но носить можно',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          11: {'id': 3,
              'type': 'jeans',
              'image': 'images/jeans/jeans_3.jpg',
              'name': 'Джинсы ништяковые',
              'description': 'Возможно их когда-то носил сам Леонтьев',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          12: {'id': 4,
              'type': 'jeans',
              'image': 'images/jeans/jeans_4.jpg',
              'name': 'Очень ДОРОГИЕ джинсы',
              'description': 'Их цена как бюджет Монголии',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 1500},
          13: {'id': 5,
              'type': 'jeans',
              'image': 'images/jeans/jeans_5.jpg',
              'name': 'Джинсы в которых хоронили Жириновского',
              'description': 'no comment',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          14: {'id': 1,
              'type': 'shoes',
              'image': 'images/shoes/shoes_1.jpg',
              'name': 'Черивички',
              'description': 'Царские, золоченые',
              'size': [32, 34, 36, 40, 24],
              'quantity': 3,
              'price': 3200},
          15: {'id': 2,
               'type': 'shoes',
               'image': 'images/shoes/shoes_2.jpg',
               'name': 'Тапки-говнодавы',
               'description': 'Помесить говно в деревне в самый раз',
               'size': [32, 34, 36, 40, 24],
               'quantity': 3,
               'price': 3200},
          16: {'id': 3,
               'type': 'shoes',
               'image': 'images/shoes/shoes_3.jpg',
               'name': 'Модные педали',
               'description': 'Шнурки в комплекте',
               'size': [32, 34, 36, 40, 24],
               'quantity': 3,
               'price': 3200},
          17: {'id': 4,
               'type': 'shoes',
               'image': 'images/shoes/shoes_4.jpg',
               'name': 'Сандалии',
               'description': 'Носить только с носками',
               'size': [32, 34, 36, 40, 24],
               'quantity': 3,
               'price': 1500},
          18: {'id': 5,
               'type': 'shoes',
               'image': 'images/shoes/shoes_5.jpeg',
               'name': 'ADIBAS',
               'description': 'Фирменные шузы',
               'size': [32, 34, 36, 40, 24],
               'quantity': 3,
               'price': 3200}}
